= Array with Secondary Keys

Wraps a PHP array and maintains secondary lookup maps, for fast retrieval of items by nested field values.

This is conceptually similar to how secondary keys in databases work.

== Features

Implements `Iterator` and `Countable` interfaces, so you can use `foreach`, `count`, etc. like on a normal PHP array.

Implemented in pure PHP. Secondary indexes are implemented as PHP associative arrays -- hash tables with O(1) average lookup time.

== API Reference

A "document" is the value associated to a primary key. It can be of any type. If the document is an array, secondary indexes can be specified using the "dot" notation.

All created secondary key indexes are automatically updated when adding/removing/updating values.

=== Constructor
[source,php]
----
ArrayWithSecondaryKeys(array $array = [])
----
Creates a new `ArrayWithSecondaryKeys` collection, initialized from the given array. If called without arguments, an empty collection is created.

== containsPrimaryKey
[source,php]
----
containsPrimaryKey($key): bool
----
Checks if the specified primary key is present in the collection.

== containsSecondaryKey
[source,php]
----
containsSecondaryKey($index, $key): bool
----
Checks if the specified secondary key is present in the specified index.

=== count
[source,php]
----
count(): int
----
Returns the number of documents in the collection.

=== get
[source,php]
----
get($key, $default = null): mixed
----
Retrieves a document by key.

If the key is given in "dot" notation, the corresponding nested part of the document is returned. If the key is not a string that includes a dot, it is treated as a primary key.

=== has
[source,php]
----
has($key): bool
----
Check if an item or items exist in the collection using "dot" notation.


=== isEmpty
[source,php]
----
isEmpty(): bool
----
Returns `true` if there are no primary keys in the collection, `false` otherwise.

=== put
[source,php]
----
put($key, $document)
----
Adds a new document to the collection under the given key.

If the key is given in "dot" notation, and the top level primary key exists, a nested part is added to the existing document.

If the key is not a string that includes a dot, it is treated as a primary key.

=== remove
[source,php]
----
remove($key)
----
Removes the document associated with the given primary key, or removes a nested part of the document if key is given in "dot" notation.

If the key is given in "dot" notation, the corresponding nested part of the document is removed. If the key is not a string that includes a dot, it is treated as a primary key.

=== updateSecondaryKey
[source,php]
----
updateSecondaryKey($index, $existingValue, $newValue)
----
Finds the document by existing value of secondary key and updates the existing value of secondary key in the document to new value.

Returns the primary key of the updated document, or `null` if a document with existing value is not found.

=== append
[source,php]
----
append($document)
----
Appends a document (using `[]=`).

=== createIndex
[source,php]
----
createIndex($index)
----
Creates and new index and indexes existing document. Index is given as string in "dot" notation (e.g. `state.pid`).

=== getByIndex
[source,php]
----
getByIndex($index, $secondaryKey, $default = null): mixed
----
Retrieves a document by index (secondary key). Index is given as string in "dot" notation (e.g. `state.pid`).

Throws `VladimirVrzic\ArrayWithSecondaryKeys\NoSuchIndexException` if the given index does not exist.

=== updateByIndex
[source,php]
----
updateByIndex($index, $secondaryKey, $document)
----
Updates a document by index (secondary key). Index is given as string in "dot" notation (e.g. `state.pid`).

Throws `VladimirVrzic\ArrayWithSecondaryKeys\NoSuchIndexException` if the given index does not exist.

Returns `true` if the existing document associated with the given secondary key was found and replaced. Returns `false` if the document associated with the given secondary key was not found.

=== removeByIndex
[source,php]
----
removeByIndex($index, $secondaryKey)
----
Removes a document by index (secondary key).  Index is given as string in "dot" notation (e.g. `state.pid`).

Throws `VladimirVrzic\ArrayWithSecondaryKeys\NoSuchIndexException` if the given index does not exist.

Returns `true` if the document associated with the given secondary key was found and removed. Returns `false` if a document associated with the given secondary key was not found.

=== putIfAbsent
[source,php]
----
putIfAbsent($key, $document): mixed
----
If the key doesn't exist, adds the new key associated with the given document and returns `null`.

If the key exists, returns the current document.

=== asArray
[source,php]
----
asArray(): array
----
Returns a copy of the array as a normal PHP array (without secondary indexes).

=== primaryKeys
[source,php]
----
primaryKeys(): array
----
Returns an array of all primary keys.

=== secondaryKeys
[source,php]
----
secondaryKeys($index): array
----
Returns an array of all secondary keys associated with the given index.

== Setup

Add the following to your `composer.json`:

[source,php]
----
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/vrza/array-with-secondary-keys"
         }
    ],
    "require": {
        "vrza/array-with-secondary-keys": "dev-main"
    }
----

== TODO

- Implement the Iterator interface

== Name ideas

- <[associative] array | map | dictionary> with secondary keys
- multi-index <[associative] array | map | dictionary>
