= Array with Secondary Keys

Wraps a PHP array and maintains secondary indexes (similar to how secondary keys in an SQL database work).

== API Reference

A "document" is the value associated to a primary key. It can be of any type. If the document is an array, secondary indexes can be specified using the "dot" notation.

All created secondary key indexes are automatically updated when adding/removing/updating values.

=== Constructor
```
__construct(array $array = [])
```
Creates a new `ArrayWithSecondaryKeys` collection, initialized from the given array. If called without arguments, an empty array is created.

=== count
```
count(): int
```
Returns the number of documents in the collection.

=== isEmpty
```
isEmpty(): bool
```
Returns `true` if there are no primary keys in the collection, `false` otherwise.

=== put
```
put($key, $document)
```
Adds a new document to the collection under the given key.

If the key is given in "dot" notation, and the top level primary key exists, a nested part is added to the existing document.

If the key is not a string that includes a dot, it is treated as a primary key.

=== get
```
get($key, $default = null): mixed
```
Retrieves a document by key.

If the key is given in "dot" notation, the corresponding nested part of the document is returned. If the key is not a string that includes a dot, it is treated as a primary key.

=== remove
```
remove($key)
```
Removes the document associated with the given primary key, or removes a nested part of the document if key is given in "dot" notation.

If the key is given in "dot" notation, the corresponding nested part of the document is removed. If the key is not a string that includes a dot, it is treated as a primary key.

=== append
```
append($document)
```
Appends a document (using `[]=`).

=== createIndex
```
createIndex($index)
```
Creates and new index and indexes existing document. Index is given as string in "dot" notation (e.g. `state.pid`).

=== getByIndex
```
getByIndex($index, $secondaryKey, $default = null): mixed
```
Retrieves a document by index (secondary key). Index is given as string in "dot" notation (e.g. `state.pid`). Throws `VladimirVrzic\ArrayWithSecondaryKeys\NoSuchIndexException` if index is not present.

=== updateByIndex
```
updateByIndex($index, $secondaryKey, $document)
```
Updates a document by index (secondary key). Index is given as string in "dot" notation (e.g. `state.pid`).

Throws `VladimirVrzic\ArrayWithSecondaryKeys\NoSuchIndexException` if the given index does not exist.

Returns `true` if the existing document associated with the given secondary key was found and replaced. Returns `false` if the document associated with the given secondary key was not found.

=== removeByIndex
```
removeByIndex($index, $secondaryKey)
```
Removes a document by index (secondary key).  Index is given as string in "dot" notation (e.g. `state.pid`).

Throws `VladimirVrzic\ArrayWithSecondaryKeys\NoSuchIndexException` if the given index does not exist.

Returns `true` if the document associated with the given secondary key was found and removed. Returns `false` if a document associated with the given secondary key was not found.

=== putIfAbsent
```
putIfAbsent($key, $document): mixed
```
If the key doesn't exist, puts the new document into the array and returns `null`.

If the key exists, returns the existing document associated with it.

=== asArray
```
asArray(): array
```
Returns a copy of the array as a normal PHP array (without secondary indexes).

=== primaryKeys
```
primaryKeys(): array
```
Returns an array of all primary keys.

=== secondaryKeys
```
secondaryKeys($index): array
```
Returns an array of all secondary keys associated with the given index.

== Name ideas

- <[associative] array | map | dictionary> with secondary keys
- multi-index <[associative] array | map | dictionary>
